### PR TITLE
Completed css-four-column-layout challenge. -Lindsey Laveirge

### PR DESCRIPTION
**Pull request by llaveirge**
With the most condensed CSS yet! (Hopefully not too condensed...) 

four-column-layout-screenshot

### CODE REVIEW

**Review by BrettAlbright — CHANGES_REQUESTED** [review]
looks great! Just make sure to wrap the images with column divs!

**Comment by llaveirge** [comment]
I went out of comfort zone not wrapping and spent a lot of time wondering if I should have! Excellent, will do!

**Comment by llaveirge** [comment]
New screenshot. 
four-column-layout-screenshot-2

**Review by BrettAlbright — APPROVED** [review]
👍🏼

**Pull request merged**
